export const mapslided = [
  {
    parkimg: "/homepage/pcard/ch4be.png",
    title: "KSH Chakan IV",
    city: "Pune, Maharashtra",
    tarea: "0.36 MN. SQ. FT.",
    parkLink: "/ksh-chakan-iv",
    tbuild: "02 BUILDINGS",
  },
  {
    parkimg: "/homepage/pcard/ch3be.png",
    title: "KSH Chakan III",
    city: "Pune, Maharashtra",
    tarea: "1.5 MN. SQ. FT.",
    parkLink: "/ksh-chakan-iii",
    tbuild: "08 BUILDINGS",
  },
  {
    parkimg: "/homepage/pcard/ch2be.png",
    title: "KSH Chakan II",
    city: "Pune, Maharashtra",
    tarea: "1.2 MN. SQ. FT.",
    parkLink: "/ksh-chakan-ii",
    tbuild: "05 BUILDINGS",
  },
  {
    parkimg: "/homepage/pcard/ch1be.png",
    title: "KSH Chakan I",
    city: "Pune, Maharashtra",
    tarea: "0.85 MN. SQ. FT.",
    parkLink: "/ksh-chakan-i",
    tbuild: "04 BUILDINGS",
  },
  {
    parkimg: "/homepage/pcard/tal1be.png",
    title: "KSH Talegaon I",
    city: "Pune, Maharashtra",
    tarea: "0.14 MN. SQ. FT.",
    parkLink: "/ksh-talegaon-i",
    tbuild: "02 BUILDINGS",
  },
];
export const mapslided2 = [
  {
    parkimg: "/homepage/pcard/hosurmapbe.png",
    title: "KSH Hosur I",
    city: "Hosur, Tamil Nadu",
    tarea: "1.2 MN. SQ.FT.",
    parkLink: "/ksh-hosur-i",
    tbuild: "05 BUILDINGS",
  },
];
export const mapslided3 = [
  {
    parkimg: "/homepage/pcard/hosurmapbe.png",
    title: "Upcoming",
    city: "Hosur, Tamil Nadu",
    tarea: "1 MN. SQ.FT.",
    parkLink: "/ksh-hosur-i",
    tbuild: "05 BUILDINGS",
  },
];
export const hotspotData = {
  desktop: [
    {
      id: 1,
      park_no: "05",
      park_name: "Pune",
      x: "46%",
      y: "59%",
      scale: 2,
      translateX: -8,
      translateY: -8,
      clickEvents: true,
      upComing: false,
      dots: 5,
    },
    {
      id: 2,
      park_no: "01",
      park_name: "Bangalore",
      x: "48.7%",
      y: "70%",
      scale: 2,
      translateX: -8,
      translateY: -8,
      clickEvents: true,
      upComing: false,
      dots: 1,
    },
    {
      id: 3,
      park_no: "01",
      park_name: "Chennai<br/>(Upcoming)",
      x: "52%",
      y: "73%",
      scale: 2,
      translateX: -8,
      translateY: -8,
      clickEvents: false,
      upComing: true,
      dots: 1,
    },
  ],
  tablet: [
    {
      id: 1,
      park_no: "05",
      park_name: "Pune",
      x: "38%",
      y: "66%",
      scale: 1.8,
      translateX: -6,
      translateY: -6,
      clickEvents: true,
      upComing: false,
      dots: 5,
    },
    {
      id: 2,
      park_no: "01",
      park_name: "Bangalore",
      x: "42%",
      y: "65%",
      scale: 1.8,
      translateX: -6,
      translateY: -6,
      clickEvents: true,
      upComing: false,
      dots: 1,
    },
    {
      id: 3,
      park_no: "01",
      park_name:
        "Chennai<br/><span className='uptext text-red-500'>(Upcoming)</span>",
      x: "48.7%",
      y: "71%",
      scale: 2,
      translateX: -8,
      translateY: -8,
      clickEvents: false,
      upComing: true,
      dots: 1,
    },
  ],
  mobile: [
    {
      id: 1,
      park_no: "05",
      park_name: "Pune",
      x: "26%",
      y: "59%",
      scale: 2,
      translateX: -8,
      translateY: -8,
      clickEvents: true,
      upComing: false,
      dots: 5,
    },
    {
      id: 2,
      park_no: "01",
      park_name: "Bangalore",
      x: "36%",
      y: "69%",
      scale: 2,
      translateX: -8,
      translateY: -8,
      clickEvents: true,
      upComing: false,
      dots: 1,
    },
    {
      id: 3,
      park_no: "01",
      park_name: "Chennai<br/>(Upcoming)",
      x: "42%",
      y: "75%",
      scale: 2,
      translateX: -8,
      translateY: -8,
      clickEvents: false,
      upComing: true,
      dots: 1,
    },
  ],
};
